---
title: "Reputational Pressure Pilot Data Analysis"
author: "Kaelin Main"
date: "2026-07-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(viridis)
```


```{r read-data}
data <- read_excel("pilot_data/rep_pressure_simplified.xlsx")
```

```{r clean-data}
data <- data %>% 
  mutate(condition_binary = if_else(condition == "high rep pressure", 1, 0)) %>%
  mutate(trialfirst_binary = if_else(`trial first` == "high", 1, 0)) %>% 
  rename(choice = `choice combination code`) %>% 
  mutate(choice = as.factor(choice))
```

```{r}
data <- data %>%
  mutate(
    hc_choice = case_when(
      choice == 1 ~ "book",
      choice == 2 ~ "toy",
      choice == 3 ~ "toy",
      choice == 4 ~ "book"
    ),
    lc_choice = case_when(
      choice == 1 ~ "book",
      choice == 2 ~ "toy",
      choice == 3 ~ "book",
      choice == 4 ~ "toy"
    )
  )
```


```{r plot}
  ggplot(data, aes(fill = choice, x = condition)) +
    geom_bar(position = "fill", width = 0.6) +
    labs(x = "Condition",
         y = " ") +
    scale_x_discrete(labels = c("High reputational pressure", "Low reputational pressure")) +
    scale_fill_discrete(
      labels = c("Book for both questions",
                 "Toy for both questions",
                 "Book for low certainty, toy for high certainty",
                 "Toy for low certainty, book for high certainty"),
      name = "Choice"
    ) +
    theme_minimal(base_size = 11)

  ggplot(data, aes(fill = choice, x = condition)) +
    geom_bar(position = "dodge", width = 0.6) +
    labs(x = "Condition",
         y = "Count") +
    scale_x_discrete(labels = c("High reputational pressure", "Low reputational pressure")) +
    scale_fill_discrete(
      labels = c("Book for both questions",
                 "Toy for both questions",
                 "Book for low certainty, toy for high certainty",
                 "Toy for low certainty, book for high certainty"),
      name = "Choice"
    ) +
    theme_minimal(base_size = 12)
```

```{r plot-wrapped}

data <- data %>% 
  mutate(trialfirst_binary = as.factor(trialfirst_binary)) %>%
  mutate(condition_binary = as.factor(condition_binary))

  ggplot(data, aes(x = trialfirst_binary, fill = choice)) +
    geom_bar(position = "dodge", width = 0.6) + 
    facet_wrap(~condition_binary, labeller = as_labeller(c(
      "0" = "Low reputational pressure",
      "1" = "High reputational pressure"
    ))) +
    labs(x = "Trial order",
         y = "Count") +
    scale_x_discrete(labels = c("Low cert first", "High cert first")) +
    scale_fill_discrete(
      labels = c("Book for both questions",
                 "Toy for both questions",
                 "Book for low certainty, toy for high certainty",
                 "Toy for low certainty, book for high certainty"),
      name = "Choice"
    ) 
    

```

```{r make-prop-data-set}

data_high <- data %>% filter(condition_binary == 1)  # high reputational pressure
data_low  <- data %>% filter(condition_binary == 0)  # low reputational pressure

prop_high <- data_high %>%
  summarise(
    hc = mean(hc_choice == "book"),
    lc = mean(lc_choice == "book")
  ) %>%
  pivot_longer(cols = c(hc, lc), names_to = "choice_type", values_to = "prop_book") %>%
  mutate(condition = "high")

prop_low <- data_low %>%
  summarise(
    hc = mean(hc_choice == "book"),
    lc = mean(lc_choice == "book")
  ) %>%
  pivot_longer(cols = c(hc, lc), names_to = "choice_type", values_to = "prop_book") %>%
  mutate(condition = "low")

prop_data <- bind_rows(prop_high, prop_low)
```


```{r}
prop_data_seg <- prop_data %>%
  mutate(prop_toy = 1 - prop_book) %>%
  pivot_longer(cols = c(prop_book, prop_toy), names_to = "response", values_to = "proportion") %>%
  mutate(response = recode(response, prop_book = "book", prop_toy = "toy"))

ggplot(prop_data_seg, aes(x = choice_type, y = proportion, fill = response)) +
  geom_col() +
  facet_wrap(
    ~ condition,
    labeller = as_labeller(c(high = "High Rep Pressure", low = "Low Rep Pressure"))
  ) +
  scale_y_continuous(breaks = c(0, 1), labels = c("toy", "book")) +
  labs(x = "Choice type", y = NULL) +
  theme_bw() + 
  theme(legend.position = "none")
```
```{r modelling}
model1 <- lm(lc_choice ~ condition_binary, data = data)
```



